### ISSUE TITLE
add support with BentoBox

### ISSUE THREAD

**Issue by disqetow** [josemmo/yamipa#118]
My server have bskyblock, I put image on island, and it disappear when server restart.
lastest yamipa and pufferfish 1.20.4

[23:39:19 ERROR]: [YamipaPlugin] [ImageRenderer] Invalid fake image properties: 1;bskyblock_world;1;84;0;UP;NONE;4;4;1711208333;55837a1a-3718-3024-adc9-dfed0e138254;7
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at io.josemmo.bukkit.plugin.renderer.ImageRenderer.loadConfig(ImageRenderer.java:125) ~[YamipaPlugin-1.3.0.jar:?]
        at io.josemmo.bukkit.plugin.renderer.ImageRenderer.start(ImageRenderer.java:72) ~[YamipaPlugin-1.3.0.jar:?]
        at io.josemmo.bukkit.plugin.YamipaPlugin.onEnable(YamipaPlugin.java:116) ~[YamipaPlugin-1.3.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by josemmo** [comment]
Hello @disqetow,

Thanks for your report!

This happens because Yamipa is loaded before the worlds managed by BentoBox are available to the server (in your case, "bskyblock_world"). Hopefully it shouldn't be difficult to fix.

**Comment by josemmo** [comment]
Hi, @disqetow!

Could you verify that this issue is now fixed in the [v1.3.2-SNAPSHOT](https://github.com/josemmo/yamipa/releases/download/v1.3.2-SNAPSHOT/YamipaPlugin-1.3.2-SNAPSHOT.jar) pre-release version of Yamipa?

**Comment by disqetow** [comment]
> Hi, @disqetow!
> 
> Could you verify that this issue is now fixed in the [v1.3.2-SNAPSHOT](https://github.com/josemmo/yamipa/releases/download/v1.3.2-SNAPSHOT/YamipaPlugin-1.3.2-SNAPSHOT.jar) pre-release version of Yamipa?

no, it didnt fix, same as prev version.

**Comment by josemmo** [comment]
I created a server with:
- Pufferfish 1.20.4 build 47 (although keep in mind this server is not officially supported by Yamipa)
- BentoBox 2.2.0 (including addons from Classic Skyblock variant)
- ProtocolLib 5.2.0-SNAPSHOT-679
- Yamipa 1.3.2-SNAPSHOT

After configurating the server, creating an island, and placing a couple of images, I restarted the server several times. I **cannot** reproduce this bug after the update:
```
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8+7) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[10:17:02 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:17:04 INFO]: Loaded 1174 recipes
[10:17:04 INFO]: Loaded 1271 advancements
[10:17:04 INFO]: Starting minecraft server version 1.20.4
[10:17:04 INFO]: Loading properties
[10:17:04 INFO]: This server is running Pufferfish version git-Pufferfish-47 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9d12215 on HEAD)
[10:17:05 INFO]: Server Ping Player Sample Count: 12
[10:17:05 INFO]: Using 4 threads for Netty based IO
[10:17:05 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and gen parallelism of 2 threads
[10:17:05 WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[10:17:05 WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[10:17:05 WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[10:17:05 WARN]: [Pufferfish] Debug: Java: 17.0.8, test run: true
[10:17:05 INFO]: Default game type: SURVIVAL
[10:17:05 INFO]: Generating keypair
[10:17:05 INFO]: Starting Minecraft server on *:25565
[10:17:05 INFO]: Using default channel type
[10:17:05 INFO]: Paper: Using Java compression from Velocity.
[10:17:05 INFO]: Paper: Using Java cipher from Velocity.
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loading 5 libraries... please wait
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loaded library C:\Users\josemmo\Desktop\pufferfish-bentobox\libraries\mysql\mysql-connector-java\8.0.27\mysql-connector-java-8.0.27.jar
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loaded library C:\Users\josemmo\Desktop\pufferfish-bentobox\libraries\com\google\protobuf\protobuf-java\3.11.4\protobuf-java-3.11.4.jar
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loaded library C:\Users\josemmo\Desktop\pufferfish-bentobox\libraries\org\mariadb\jdbc\mariadb-java-client\3.0.5\mariadb-java-client-3.0.5.jar
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loaded library C:\Users\josemmo\Desktop\pufferfish-bentobox\libraries\org\postgresql\postgresql\42.2.18\postgresql-42.2.18.jar
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loaded library C:\Users\josemmo\Desktop\pufferfish-bentobox\libraries\org\checkerframework\checker-qual\3.5.0\checker-qual-3.5.0.jar
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loaded library C:\Users\josemmo\Desktop\pufferfish-bentobox\libraries\org\mongodb\mongodb-driver\3.12.12\mongodb-driver-3.12.12.jar
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loaded library C:\Users\josemmo\Desktop\pufferfish-bentobox\libraries\org\mongodb\bson\3.12.12\bson-3.12.12.jar
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loaded library C:\Users\josemmo\Desktop\pufferfish-bentobox\libraries\org\mongodb\mongodb-driver-core\3.12.12\mongodb-driver-core-3.12.12.jar
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loaded library C:\Users\josemmo\Desktop\pufferfish-bentobox\libraries\com\zaxxer\HikariCP\5.0.1\HikariCP-5.0.1.jar
[10:17:06 INFO]: [SpigotLibraryLoader] [BentoBox] Loaded library C:\Users\josemmo\Desktop\pufferfish-bentobox\libraries\org\slf4j\slf4j-api\2.0.0-alpha1\slf4j-api-2.0.0-alpha1.jar
[10:17:06 INFO]: [BentoBox] Loading server plugin BentoBox v2.2.0
[10:17:06 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[10:17:07 INFO]: [YamipaPlugin] Loading server plugin YamipaPlugin v1.3.2-SNAPSHOT
[10:17:07 INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:17:07 INFO]: [BentoBox] Enabling BentoBox v2.2.0
[10:17:07 WARN]: [BentoBox] ************ Disclaimer **************
[10:17:07 WARN]: [BentoBox] BentoBox may not be compatible with this server!
[10:17:07 WARN]: [BentoBox] BentoBox is tested only on the following Spigot versions:
[10:17:07 WARN]: [BentoBox] 1.19, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20.1, 1.20.2, 1.20.3, 1.20.4
[10:17:07 WARN]: [BentoBox] **************************************
[10:17:07 INFO]: [BentoBox] Loading Settings from config.yml...
[10:17:07 INFO]: [BentoBox] Saving default panels...
[10:17:09 INFO]: [BentoBox] Loading addons...
[10:17:09 INFO]: [BentoBox-Bank] Loading server plugin BentoBox-Bank v1.7.1
[10:17:09 INFO]: [BentoBox-Biomes] Loading server plugin BentoBox-Biomes v2.1.1
[10:17:09 INFO]: [BentoBox-BSkyBlock] Loading server plugin BentoBox-BSkyBlock v1.17.1
[10:17:09 INFO]: [BentoBox-Challenges] Loading server plugin BentoBox-Challenges v1.3.0
[10:17:10 INFO]: [BentoBox-Level] Loading server plugin BentoBox-Level v2.12.0
[10:17:10 INFO]: [BentoBox-Warps] Loading server plugin BentoBox-Warps v1.14.0
[10:17:10 INFO]: [BentoBox] Loaded 8 addons.
[10:17:10 INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[10:17:10 INFO]: Preparing level "bskyblock_world"
[10:17:10 INFO]: Preparing start region for dimension minecraft:overworld
[10:17:10 INFO]: Time elapsed: 217 ms
[10:17:10 INFO]: Preparing start region for dimension minecraft:the_nether
[10:17:10 INFO]: Time elapsed: 54 ms
[10:17:10 INFO]: Preparing start region for dimension minecraft:the_end
[10:17:10 INFO]: Time elapsed: 34 ms
[10:17:10 INFO]: [YamipaPlugin] Enabling YamipaPlugin v1.3.2-SNAPSHOT
[10:17:10 INFO]: [YamipaPlugin] Running on VERBOSE mode
[10:17:10 INFO]: [YamipaPlugin] [ImageCommandBridge] Registered plugin command and aliases
[10:17:10 INFO]: [YamipaPlugin] [ImageStorage] Registered file "buah.png"
[10:17:10 INFO]: [YamipaPlugin] [ImageStorage] Registered file "gandalf-happy.gif"
[10:17:10 INFO]: [YamipaPlugin] [ImageStorage] Found 2 file(s) in images directory
[10:17:10 INFO]: [YamipaPlugin] Enabled image animation support
[10:17:10 INFO]: [YamipaPlugin] [FakeImage] Created FakeImage#(Location{world=CraftWorld{name=bskyblock_world},x=-4.0,y=80.0,z=4.0,pitch=0.0,yaw=0.0},UP) from ImageFile#(buah.png)
[10:17:10 INFO]: [YamipaPlugin] [ImageRenderer] Created WorldArea#(bskyblock_world,-1,0)
[10:17:10 INFO]: [YamipaPlugin] [FakeImage] Created FakeImage#(Location{world=CraftWorld{name=bskyblock_world},x=-4.0,y=80.0,z=0.0,pitch=0.0,yaw=0.0},UP) from ImageFile#(gandalf-happy.gif)
[10:17:10 INFO]: [YamipaPlugin] [ImageRenderer] Created WorldArea#(bskyblock_world,-1,-1)
[10:17:10 INFO]: [YamipaPlugin] Waiting for ProtocolLib to be ready...
[10:17:11 INFO]: [YamipaPlugin] [FileSystemWatcher] Started watching directory at "C:\Users\josemmo\Desktop\pufferfish-bentobox\plugins\YamipaPlugin\images"
[10:17:11 INFO]: [YamipaPlugin] Triggered map color cache warm-up
[10:17:11 INFO]: [YamipaPlugin] ProtocolLib is now ready
[10:17:11 INFO]: Running delayed init tasks
[10:17:11 INFO]: [BentoBox] Enabling game mode addons...
[10:17:11 INFO]: [BentoBox] Enabling BSkyBlock (1.17.1)...
[10:17:11 INFO]: [BentoBox] Enabling other addons...
[10:17:11 INFO]: [BentoBox] Enabling Level (2.12.0)...
[10:17:11 WARN]: [BentoBox] [Level] Level Addon: No such world in blockconfig.yml : caveblock-world
[10:17:11 WARN]: [BentoBox] [Level] Level Addon: No such world in blockconfig.yml : acidisland_world
[10:17:11 INFO]: [BentoBox] [Level] Level hooking into BSkyBlock
```

I don't what's causing that error in your server, but it has to be something else. Delete "images.dat" (note you will lose all placed images), try placing images, and restart the server to see if the error still occurs.

**Comment by disqetow** [comment]
hi, I delete images.dat, did I need redownload image? 

[21:13:51 INFO]: [YamipaPlugin] Enabling YamipaPlugin v1.3.2-SNAPSHOT
[21:13:51 INFO]: [YamipaPlugin] Enabled image animation support
[21:13:51 WARN]: [YamipaPlugin] [FileSystemWatcher] Device does not support inotify, detection of file changes will be slower
[21:13:51 ERROR]: [YamipaPlugin] [ImageRenderer] Invalid fake image properties: furina1;skyblock;-4;85;1003;UP;CLOCKWISE;1;1;1711717990;8ebd83cb-7396-4ab0-b1a1-542840c1ef50;7
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at io.josemmo.bukkit.plugin.renderer.ImageRenderer.loadConfig(ImageRenderer.java:125) ~[YamipaPlugin-1.3.2-SNAPSHOT.jar:?]
        at io.josemmo.bukkit.plugin.renderer.ImageRenderer.start(ImageRenderer.java:72) ~[YamipaPlugin-1.3.2-SNAPSHOT.jar:?]
        at io.josemmo.bukkit.plugin.YamipaPlugin.onEnable(YamipaPlugin.java:116) ~[YamipaPlugin-1.3.2-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by josemmo** [comment]
Hello @disqetow,

I've no idea what's going on. It must be related to how your server handles worlds, because in the first logs, the name of the world that produced the crash was "bskyblock_world" and now it's different ("skyblock"). If you just deleted "images.dat" without changing any other stuff, it doesn't make sense that the world got renamed. Either that or I'm missing something obvious.

Anyway, unfortunately I'm going to have to close this issue as I cannot reproduce it and have no clue what could be causing this.
