### ISSUE TITLE
 Disappearing Image

### ISSUE THREAD

**Issue by Yuupering** [josemmo/yamipa#122]
The image disappears every time the server is turned off and on.

The symptom did not appear when using MC 1.19.2, but the problem occurred after upgrading to 1.20.1.

[18:54:53] [Server thread/INFO]: [YamipaPlugin] Enabling YamipaPlugin v1.3.1
[18:54:53] [Server thread/INFO]: [YamipaPlugin] Enabled image animation support
[18:54:53] [Server thread/ERROR]: [YamipaPlugin] [ImageRenderer] Invalid fake image properties: skills02.png;TowerLobby;1555;4;1479;EAST;NONE;15;8;1712136186;f925b249-535e-4681-9b9e-374e746cdb66;1
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:209) ~[?:?]
	at io.josemmo.bukkit.plugin.renderer.ImageRenderer.loadConfig(ImageRenderer.java:125) ~[YamipaPlugin-1.3.1.jar:?]
	at io.josemmo.bukkit.plugin.renderer.ImageRenderer.start(ImageRenderer.java:72) ~[YamipaPlugin-1.3.1.jar:?]
	at io.josemmo.bukkit.plugin.YamipaPlugin.onEnable(YamipaPlugin.java:116) ~[YamipaPlugin-1.3.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by josemmo** [comment]
Hello @Yuupering,

What ProtocolLib version are you using? What other plugins do you have installed?
I see you're using PurpurMC, does the issue occur when using PaperMC instead?

**Comment by Yuupering** [comment]
I've been using purpur on a live server for a year so I can't confirm papermc. As for other plugins, today the protocol library was updated from 5.1.0 to 5.2.0. But the same symptoms appear. The world management plugin uses Phantom World.

**Comment by josemmo** [comment]
Hello @Yuupering,

Can you try the latest snapshot to see if it's been fixed? https://github.com/josemmo/yamipa/releases/download/v1.3.2-SNAPSHOT-b2/YamipaPlugin-1.3.2-SNAPSHOT-b2.jar

**Comment by Yuupering** [comment]
After upgrading, I turned the server off and on, but it doesn't seem to go away. If it disappears, I will leave it as an issue again. thank you!

**Comment by josemmo** [comment]
Great! Thanks for letting me know :)
