### ISSUE TITLE
Invalid fake image properties, i use lastest ProtocolLib, fork leaf ( papermc ) 1.21.1

### ISSUE THREAD

**Issue by mnhatt27** [josemmo/yamipa#141]
[03:14:28] [Server thread/ERROR]: [YamipaPlugin] [ImageRenderer] Invalid fake image properties: luffy.gif;Lobby;-214;27;-196;WEST;NONE;8;5;1729539858;6e16a61a-ef73-377a-940a-b2bbb7064677;1
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at YamipaPlugin-1.3.2.jar/io.josemmo.bukkit.plugin.renderer.ImageRenderer.loadConfig(ImageRenderer.java:125) ~[YamipaPlugin-1.3.2.jar:?]
	at YamipaPlugin-1.3.2.jar/io.josemmo.bukkit.plugin.renderer.ImageRenderer.start(ImageRenderer.java:72) ~[YamipaPlugin-1.3.2.jar:?]
	at YamipaPlugin-1.3.2.jar/io.josemmo.bukkit.plugin.YamipaPlugin.onEnable(YamipaPlugin.java:116) ~[YamipaPlugin-1.3.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.21.1.jar:1.21.1-DEV-e324f59]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.1.jar:1.21.1-DEV-e324f59]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:660) ~[leaf-1.21.1.jar:1.21.1-DEV-e324f59]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:609) ~[leaf-1.21.1.jar:1.21.1-DEV-e324f59]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[leaf-1.21.1.jar:1.21.1-DEV-e324f59]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:505) ~[leaf-1.21.1.jar:1.21.1-DEV-e324f59]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:378) ~[leaf-1.21.1.jar:1.21.1-DEV-e324f59]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[leaf-1.21.1.jar:1.21.1-DEV-e324f59]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-e324f59]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by josemmo** [comment]
Hello @mnhatt27,

Are you using any multi-world plugin o have you renamed the "Lobby" world recently?

**Comment by mnhatt27** [comment]
> Hello @mnhatt27,
> 
> Are you using any multi-world plugin o have you renamed the "Lobby" world recently?

Yes i have, I moved my lobby world file to the server, and used this plugin "https://www.spigotmc.org/resources/worldmanager.117043/" to load the world
