### ISSUE TITLE
YamipaPlugin v1.3.2 generated an exception java.lang.NullPointerException: constructor

### ISSUE THREAD

**Issue by reamianv** [josemmo/yamipa#142]
[11:07:04] [Server thread/WARN]: [YamipaPlugin] Task #24098 for YamipaPlugin v1.3.2 generated an exception
java.lang.NullPointerException: constructor
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
	at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getConstructorAccessor(MethodHandleHelper.java:70) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.accessors.Accessors.getConstructorAccessor(Accessors.java:167) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.accessors.Accessors.getConstructorAccessor(Accessors.java:145) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.LegacyDataWatcher.newHandle(LegacyDataWatcher.java:113) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.LegacyDataWatcher.<init>(LegacyDataWatcher.java:108) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.LegacyDataWatcher.<init>(LegacyDataWatcher.java:85) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.<init>(WrappedDataWatcher.java:86) ~[ProtocolLib.jar:?]
	at io.josemmo.bukkit.plugin.packets.EntityMetadataPacket.<init>(EntityMetadataPacket.java:19) ~[YamipaPlugin-1.3.2.jar:?]
	at io.josemmo.bukkit.plugin.renderer.FakeItemFrame.getRenderPackets(FakeItemFrame.java:156) ~[YamipaPlugin-1.3.2.jar:?]
	at io.josemmo.bukkit.plugin.renderer.FakeImage.spawnOnceLoaded(FakeImage.java:454) ~[YamipaPlugin-1.3.2.jar:?]
	at io.josemmo.bukkit.plugin.renderer.FakeImage.spawn(FakeImage.java:417) ~[YamipaPlugin-1.3.2.jar:?]
	at io.josemmo.bukkit.plugin.renderer.ImageRenderer.onPlayerLocationChange(ImageRenderer.java:419) ~[YamipaPlugin-1.3.2.jar:?]
	at io.josemmo.bukkit.plugin.renderer.ImageRenderer.lambda$onPlayerTeleport$3(ImageRenderer.java:456) ~[YamipaPlugin-1.3.2.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by josemmo** [comment]
Hello @reamianv,

Which version of ProtocolLib are you using?

**Comment by reamianv** [comment]
The version of the Protocol lib I've been testing with is
purpur 1.20.1 + packet event
yamipa 1.3.2 / protocollib 5.3.0 and this is what I observed.

So I changed the protocollib to 5.0.0, which was working fine, so yamipa was childish and changed the protocollib to 5.0.0, but the same thing, the image is not visible. So I made a backup and created the image in the location, and although it said that the image was created, the image is not visible. I went through the same process with the protocollib 5.3.0 version.

After that I went back to yamipa 1.3.2 beta , protocollib 5.0.0.

Translated with DeepL.com (free version)
