### ISSUE TITLE
Failed to render GIF

### ISSUE THREAD

**Issue by artemr13** [josemmo/yamipa#17]
Hi, I have issue with rendering GIFs.
Plugins used:
- ProtocolLib v4.8.0-SNAPSHOT-b539
- Yamipa v1.2.0
When I spawn GIF frame, It turns red and I have next in console (verbose logging enabled):

````
[20:19:39] [Server thread/INFO]: flex7r issued server command: /images place g 2 2
[20:19:39] [Server thread/INFO]: [YamipaPlugin] Created PlayerInteractionListener singleton
[20:19:39] [Server thread/INFO]: [YamipaPlugin] Destroyed PlayerInteractionListener singleton
[20:19:39] [Server thread/INFO]: [YamipaPlugin] Created FakeImage#(Location{world=CraftWorld{name=world},x=-225.0,y=94.0,z=115.0,pitch=0.0,yaw=0.0},NORTH) from ImageFile#(g)
[20:19:40] [pool-10-thread-3/INFO]: [YamipaPlugin] Created FakeMap#2147483607

[20:19:40] [pool-10-thread-3/ERROR]: [YamipaPlugin] Failed to render image(s) from file "E:\serva4ok\plugins\YamipaPlugin\images\g"
java.lang.ArrayIndexOutOfBoundsException: Index 4096 out of bounds for length 4096
	at com.sun.imageio.plugins.gif.GIFImageReader.read(GIFImageReader.java:1013) ~[?:?]
	at javax.imageio.ImageReader.read(ImageReader.java:938) ~[?:?]
	at io.josemmo.bukkit.plugin.storage.ImageFile.renderImages(ImageFile.java:120) ~[YamipaPlugin-1.2.0.jar:?]
	at io.josemmo.bukkit.plugin.storage.ImageFile.getMapsAndSubscribe(ImageFile.java:247) ~[YamipaPlugin-1.2.0.jar:?]
	at io.josemmo.bukkit.plugin.storage.ImageFile.getMapsAndSubscribe(ImageFile.java:197) ~[YamipaPlugin-1.2.0.jar:?]
	at io.josemmo.bukkit.plugin.renderer.FakeImage.load(FakeImage.java:297) ~[YamipaPlugin-1.2.0.jar:?]
	at io.josemmo.bukkit.plugin.renderer.FakeImage.lambda$spawn$12(FakeImage.java:332) ~[YamipaPlugin-1.2.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:19:40] [pool-10-thread-3/INFO]: [YamipaPlugin] Created FakeItemFrame#536870996 using 1 FakeMap(s)
[20:19:40] [pool-10-thread-3/INFO]: [YamipaPlugin] Created FakeItemFrame#536870997 using 1 FakeMap(s)
[20:19:40] [pool-10-thread-3/INFO]: [YamipaPlugin] Created FakeItemFrame#536870998 using 1 FakeMap(s)
[20:19:40] [pool-10-thread-3/INFO]: [YamipaPlugin] Created FakeItemFrame#536870999 using 1 FakeMap(s)
[20:19:40] [pool-10-thread-3/INFO]: [YamipaPlugin] Sent pixels for FakeMap#2147483607 to Player#flex7r
````

**Comment by artemr13** [comment]
UPD: I tried to upload another one gif, so it worked.
You can close it, but maybe you decide to update gif read code?

**Comment by artemr13** [comment]
UPD: I tried to upload another one gif, so it worked.
