### ISSUE TITLE
Error 1.18.1

### ISSUE THREAD

**Issue by TheIntelloBox** [josemmo/yamipa#22]
[19:35:57] [pool-20-thread-1/ERROR]: [YamipaPlugin] Failed to send FakeEntity packet
java.lang.IllegalArgumentException: receiver cannot be NULL.
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:698) ~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:687) ~[ProtocolLib (1).jar:?]
	at io.josemmo.bukkit.plugin.renderer.FakeEntity.tryToSendPacket(FakeEntity.java:55) ~[YamipaPlugin-1.2.1.jar:?]
	at io.josemmo.bukkit.plugin.renderer.FakeItemFrame.destroy(FakeItemFrame.java:158) ~[YamipaPlugin-1.2.1.jar:?]
	at io.josemmo.bukkit.plugin.renderer.FakeImage.lambda$destroy$13(FakeImage.java:421) ~[YamipaPlugin-1.2.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by josemmo** [comment]
Hello @TheIntelloBox,

Please provide additional information regarding the issue:
- What server are using?
- What version of ProtocolLib do you have installed?
- What steps did you follow to get the previous exception?

**Comment by TheIntelloBox** [comment]
Hello,

Paper 1.18.1
Latest dev build
I placed a picture, it worked very well but I had this error in the console.

**Comment by josemmo** [comment]
Does this happen every time you place an image? Does it also happen when removing images? Do other players see the image at the time of placing?

Looking at the exception I'm guessing this is caused by `Bukkit.getPlayer()` returning `null`:
https://github.com/josemmo/yamipa/blob/b5b4708783e8785eadae9630ecc010fe45beffd2/src/main/java/io/josemmo/bukkit/plugin/renderer/ImageRenderer.java#L344-L350

The weird thing is that it should return `null` for an online player.

Did the error happen at the same time a player disconnected or moved to another WorldArea? Make sure you have `verbose: true` in your "YamipaPlugin/config.yml" file to log debug messages.

**Comment by josemmo** [comment]
Closed due to inactivity.
