### ISSUE TITLE
Error on 1.16.5 with yamipa latest version

### ISSUE THREAD

**Issue by vSKAH** [josemmo/yamipa#26]
`[12:20:57 ERROR]: Could not pass event HangingPlaceEvent to YamipaPlugin v1.2.1
java.lang.NoSuchMethodError: 'org.bukkit.inventory.ItemStack org.bukkit.event.hanging.HangingPlaceEvent.getItemStack()'
        at io.josemmo.bukkit.plugin.renderer.ItemService.onPlaceItem(ItemService.java:98) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor809.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.ItemHanging.a(ItemHanging.java:73) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.ItemStack.placeItem(ItemStack.java:289) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:597) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1843) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:10) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1469) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[purpur-server-1.16.5-R0.1-SNAPSHOT.jar:git-Purpur-"53ac6a9"]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by josemmo** [comment]
Hello, @vSKAH,

Please provide additional information about this bug and change the issue name accordingly.

What steps are needed to trigger this exception? Is it consistent (always happens when following a set of steps)?
It looks you're running a snapshot of Purpur, does this still happen on the [latest 1.16.5 release](https://api.purpurmc.org/v2/purpur/1.16.5/1171/download)?

**Comment by josemmo** [comment]
Closed due to inactivity.

**Comment by josemmo** [comment]
Similar to #45.
