### ISSUE TITLE
Red frame while placing gif

### ISSUE THREAD

**Issue by zalupaonline** [josemmo/yamipa#34]
When I put a gif, it turns into red frames, I attached a photos and a gif
![image](https://user-images.githubusercontent.com/101278450/158152968-b33827ff-109c-44e5-92ab-67aa465aada9.png)
![image](https://user-images.githubusercontent.com/101278450/158153112-a093cb08-1db5-4227-8bc5-66a63787682c.png)
![kirito](https://user-images.githubusercontent.com/101278450/158153000-a4b54f98-8a31-4e44-8fd3-ed6d525fde3d.gif)

Some gifs work, some are red
URL where i downloaded this GIF: https://c.tenor.com/k3FgBeP2wwUAAAAC/kirito.gif

**Comment by zalupaonline** [comment]
URL where i downloaded this GIF: https://c.tenor.com/k3FgBeP2wwUAAAAC/kirito.gif

**Comment by josemmo** [comment]
How weird... The exception is caused by the `ImageStorage` service being `null`, which should never happen while Yamipa is running.

You must have another exception somewhere else in your logs, probably at server startup. Could you paste it here?
Do you a plugin manager plugin that may have disabled Yamipa while the server was running?

**Comment by zalupaonline** [comment]
[12:33:45 ERROR]: [YamipaPlugin] Failed to render image(s) from file "C:\Users\Артем\Documents\Servers\PlasmoVanilla\plugins\YamipaPlugin\images\kirito.gif"
java.lang.ArrayIndexOutOfBoundsException: Index 4096 out of bounds for length 4096
        at com.sun.imageio.plugins.gif.GIFImageReader.read(GIFImageReader.java:1013) ~[?:?]
        at javax.imageio.ImageReader.read(ImageReader.java:938) ~[?:?]
        at io.josemmo.bukkit.plugin.storage.ImageFile.renderImages(ImageFile.java:130) ~[YamipaPlugin-1.2.2.jar:?]
        at io.josemmo.bukkit.plugin.storage.ImageFile.getMapsAndSubscribe(ImageFile.java:257) ~[YamipaPlugin-1.2.2.jar:?]
        at io.josemmo.bukkit.plugin.storage.ImageFile.getMapsAndSubscribe(ImageFile.java:207) ~[YamipaPlugin-1.2.2.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeImage.load(FakeImage.java:342) ~[YamipaPlugin-1.2.2.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeImage.lambda$spawn$12(FakeImage.java:378) ~[YamipaPlugin-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:34:05 INFO]: CREXLIGHT issued server command: /image place kirito.gif 1 1 ANIM
[12:34:06 ERROR]: [YamipaPlugin] Failed to render image(s) from file "C:\Users\Артем\Documents\Servers\PlasmoVanilla\plugins\YamipaPlugin\images\kirito.gif"
java.lang.ArrayIndexOutOfBoundsException: null
[12:34:13 INFO]: [YamipaPlugin] Saved placed fake images to disk
[12:34:16 INFO]: CREXLIGHT issued server command: /image place kirito.gif 3 3 ANIM
[12:34:17 ERROR]: [YamipaPlugin] Failed to render image(s) from file "C:\Users\Артем\Documents\Servers\PlasmoVanilla\plugins\YamipaPlugin\images\kirito.gif"
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by josemmo** [comment]
The latest stack trace is from a different bug already being discussed in #30.

Again, do you have any exception at server startup? Do you have a plugin manager plugin that may have disabled Yamipa while the server was running?
