### ISSUE TITLE
Total server crash. Completely unstable with 1.18.2 Purpur

### ISSUE THREAD

**Issue by Wolvend** [josemmo/yamipa#35]
Running latest 1.18.2 Purpur server build with up to date plugins. Been having total inconsistency that has crashed our server 3 times. 

[02:17:19 ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "io.josemmo.bukkit.plugin.storage.ImageStorage.getAllFilenames()" because the return value of "io.josemmo.bukkit.plugin.YamipaPlugin.getStorage()" is null
        at io.josemmo.bukkit.plugin.commands.arguments.ImageFileArgument.getSuggestions(ImageFileArgument.java:41) ~[YamipaPlugin-1.2.2.jar:?]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:git-Purpur-1591]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:600) ~[purpur-1.18.2.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:580) ~[purpur-1.18.2.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:867) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:17:22 ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "io.josemmo.bukkit.plugin.storage.ImageStorage.getAllFilenames()" because the return value of "io.josemmo.bukkit.plugin.YamipaPlugin.getStorage()" is null
        at io.josemmo.bukkit.plugin.commands.arguments.ImageFileArgument.getSuggestions(ImageFileArgument.java:41) ~[YamipaPlugin-1.2.2.jar:?]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:git-Purpur-1591]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:600) ~[purpur-1.18.2.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:580) ~[purpur-1.18.2.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:867) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1474) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1591]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by josemmo** [comment]
Cannot reproduce on a blank server with the following specs:
- [Purpur 1.18.2 build 1591](https://api.purpurmc.org/v2/purpur/1.18.2/1591/download)
- [ProtocollLib v4.8.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.8.0)
- [Yamipa v1.2.2](https://github.com/josemmo/yamipa/releases/tag/v1.2.2)

What plugins do you have installed? What do you mean by "total server crash"? Do you have a plugin manager plugin that may have disabled Yamipa while the server was running?

**Comment by josemmo** [comment]
Any updates on this?

**Comment by josemmo** [comment]
Closing due to inactivity.
