### ISSUE TITLE
Plugin won't show images

### ISSUE THREAD

**Issue by dbourjac** [josemmo/yamipa#47]
I've tried this plugin before in Minecraft 1.17.1 version and it worked perfectly, but now in 1.19 I can't place an image, I do the same as before but when i put /place image "..." 3 3, it never gives me the option to place it like it used to. Right click to place the image. Then I try puttin the command again and it says you already have a pending action! but it doesn't give the option to place it. Then I tried give to myseld the image in the frame and when I place it the image does not show anywhere. Please help me I love your plugin so much, and when I saw you now added gifs I was so hyped <3

**Comment by josemmo** [comment]
Hello @dbourjac,

What version of Yamipa are you using? What server are you running (CraftBukkit, Spigot, Paper, etc.) and on what version?

**Comment by dbourjac** [comment]
I tried the last snapshot 1.2.4 and 1.2.3 in a Spigot server 1.19

**Comment by josemmo** [comment]
Please [enable verbose mode](https://github.com/josemmo/yamipa#configuration) and paste in this thread the logs from your server when trying to place an image.

**Comment by dbourjac** [comment]
[ERROR] Could not pass event PlayerAnimationEvent to YamipaPlugin v1.2.3

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]

at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2189) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.network.protocol.game.PacketPlayInArmAnimation.a(SourceFile:25) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.network.protocol.game.PacketPlayInArmAnimation.a(SourceFile:7) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]

at java.lang.Thread.run(Thread.java:833) [?:?]

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedChatComponent

at io.josemmo.bukkit.plugin.packets.ActionBarPacket.setText(ActionBarPacket.java:22) ~[?:?]

at io.josemmo.bukkit.plugin.utils.ActionBar.sendOnce(ActionBar.java:71) ~[?:?]

at io.josemmo.bukkit.plugin.utils.ActionBar.clear(ActionBar.java:62) ~[?:?]

at io.josemmo.bukkit.plugin.utils.SelectBlockTask.cancel(SelectBlockTask.java:90) ~[?:?]

at io.josemmo.bukkit.plugin.utils.SelectBlockTask$SelectBlockTaskListener.handle(SelectBlockTask.java:184) ~[?:?]

at io.josemmo.bukkit.plugin.utils.SelectBlockTask$SelectBlockTaskListener.onArmSwing(SelectBlockTask.java:152) ~[?:?]

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]

at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]

... 20 more

**Comment by josemmo** [comment]
Wait, what version of Protocollib are you using?

**Comment by josemmo** [comment]
Closed due to inactivity.
