### ISSUE TITLE
On starts server. More then 20 error.

### ISSUE THREAD

**Issue by valenvaio** [josemmo/yamipa#59]
On starts server. More then 20 error.

[14:50:32] [pool-89-thread-5/ERROR]: [YamipaPlugin] Failed to send FakeEntity packet
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:161) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:103) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59) ~[ProtocolLib.jar:?]
at io.josemmo.bukkit.plugin.renderer.FakeEntity.tryToSendPacket(FakeEntity.java:88) ~[YamipaPlugin-1.2.5.jar:?]
at io.josemmo.bukkit.plugin.renderer.FakeItemFrame.render(FakeItemFrame.java:146) ~[YamipaPlugin-1.2.5.jar:?]
at io.josemmo.bukkit.plugin.renderer.FakeImage.nextStep(FakeImage.java:516) ~[YamipaPlugin-1.2.5.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by valenvaio** [comment]
git-Purpur-1825 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: cf6b7c3 on HEAD)
 ProtocolLib (5.0.0-SNAPSHOT-b600)
 This happens at startup, and periodically while the server is running. It is also possible when a player enters, it should be double-checked.

**Comment by josemmo** [comment]
I cannot reproduce the issue on PurpurMC 1.19.2 (build 1825) with ProtocolLib v5.0.0-SNAPSHOT-b600 and Yamipa v1.2.5.

Are you sure that exception is thrown is server startup when nobody is yet connected?
The `FakeImage.nextStep()` method is only called when a player approaches a placed image.

**Comment by valenvaio** [comment]
**After a player logs in, the error does not appear immediately.** 

[20:37:42 ERROR]: [YamipaPlugin] Failed to send FakeEntity packet
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:161) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:103) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59) ~[ProtocolLib.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeEntity.tryToSendPacket(FakeEntity.java:88) ~[YamipaPlugin-1.2.5.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeItemFrame.render(FakeItemFrame.java:146) ~[YamipaPlugin-1.2.5.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeImage.nextStep(FakeImage.java:516) ~[YamipaPlugin-1.2.5.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:37:42 WARN]: [dwg-oasisdesert] Plugin is up to date.
[20:49:48 INFO]: ========================
[20:49:48 INFO]: Игроки онлайн 0/100
[20:49:48 INFO]: ========================
[20:49:54 INFO]: UUID of player Tatyana_Snus is 3d3ac104-0005-3211-a663-26b866103980
[20:49:54 INFO]: [CMI] CMIB proxy plugin detected
[20:49:54 WARN]: [CMI] Loaded class me.TechsCode.UltraPermissions.UltraPermissions from UltraPermissions v5.3.1 which is not a depend or softdepend of this plugin.
[20:49:54 INFO]: Tatyana_Snus[/176.196.173.204:38833] logged in with entity id 4421 at ([world]3876.7000000079474, 64.0, -16955.299999992054)
[20:49:55 INFO]: UUID of player MRX_Uchiha is 234a0b88-b0e2-3def-a45b-e1c96c3db3f9
[20:49:56 INFO]: MRX_Uchiha[/212.164.38.52:57501] logged in with entity id 4750 at ([world]4015.758437460221, 56.0, -16879.841577739287)
[20:49:59 INFO]: ========================
[20:49:59 INFO]: Игроки онлайн 2/100
[20:49:59 INFO]: Player: Tatyana_Snus, MRX_Uchiha
[20:49:59 INFO]: ========================

**Comment by josemmo** [comment]
Wow, that's quite a long list of plugins... 😬

Can you create a local copy of your server, remove/disable all plugins and start enabling them until you find which one is causing the exception?

It's probably a plugin that has ProtocolLib as a dependency.

**Comment by valenvaio** [comment]
https://www.theprogrammersworld.net/Herobrine/download.php
Herobrine v2.4.0
This plugin causes an error. It appears after posting png and gif pictures.

**Comment by josemmo** [comment]
Nice catch! I'll prepare a fix for next version.
