### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thiagogebrimm** [josemmo/yamipa#89]
```
[13:40:22 ERROR]: Could not pass event PlayerJoinEvent to YamipaPlugin v1.2.9
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.PacketPlayOutSpawnEntity
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$2(StructureCache.java:97) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:101) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:111) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) ~[ProtocolLib.jar:?]
        at io.josemmo.bukkit.plugin.packets.SpawnEntityPacket.<init>(SpawnEntityPacket.java:25) ~[YamipaPlugin-1.2.9.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeItemFrame.spawn(FakeItemFrame.java:112) ~[YamipaPlugin-1.2.9.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeImage.spawnOnceLoaded(FakeImage.java:434) ~[YamipaPlugin-1.2.9.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeImage.spawn(FakeImage.java:402) ~[YamipaPlugin-1.2.9.jar:?]
        at io.josemmo.bukkit.plugin.renderer.ImageRenderer.onPlayerLocationChange(ImageRenderer.java:395) ~[YamipaPlugin-1.2.9.jar:?]
        at io.josemmo.bukkit.plugin.renderer.ImageRenderer.onPlayerJoin(ImageRenderer.java:401) ~[YamipaPlugin-1.2.9.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor882.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1952]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:325) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:601) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1605) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by josemmo** [comment]
Hello @thiagogebrimm,

What version of ProtocolLib do you have installed?

**Comment by thiagogebrimm** [comment]
Latest dev version

**Comment by josemmo** [comment]
Ok, but could you specify which version? ProtocolLib dev builds are released quite frequently.

**Comment by josemmo** [comment]
Hello @thiagogebrimm,

Have you tried upgrading to the latest ProtocolLib release? That'd be build 636 as of today: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

This bug might be related to a new feature in 1.19.4 that should be fixed by now in ProtocolLib.

**Comment by thiagogebrimm** [comment]
solved in the last protocollib
