### ISSUE TITLE
Images are invisible and can't remove or place

### ISSUE THREAD

**Issue by Agaloth** [josemmo/yamipa#95]
After the latest update on spigot 1.2.10, images aren't working anymore.

[15:33:42 ERROR]: Could not pass event PlayerInteractEvent to YamipaPlugin v1.2.10
java.lang.IllegalStateException: Unable to set value of field private final java.lang.Iterable net.minecraft.network.protocol.BundlePacket.a
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:44) ~[ProtocolLib #638.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:359) ~[ProtocolLib #638.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:322) ~[ProtocolLib #638.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeEntity.tryToSendPackets(FakeEntity.java:111) ~[YamipaPlugin-1.2.10.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeImage.destroy(FakeImage.java:478) ~[YamipaPlugin-1.2.10.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeImage.destroy(FakeImage.java:454) ~[YamipaPlugin-1.2.10.jar:?]
        at io.josemmo.bukkit.plugin.renderer.ImageRenderer.removeImage(ImageRenderer.java:270) ~[YamipaPlugin-1.2.10.jar:?]
        at io.josemmo.bukkit.plugin.commands.ImageCommand.removeImage(ImageCommand.java:270) ~[YamipaPlugin-1.2.10.jar:?]
        at io.josemmo.bukkit.plugin.commands.ImageCommand.lambda$removeImage$3(ImageCommand.java:254) ~[YamipaPlugin-1.2.10.jar:?]
        at io.josemmo.bukkit.plugin.utils.SelectBlockTask$SelectBlockTaskListener.handle(SelectBlockTask.java:182) ~[YamipaPlugin-1.2.10.jar:?]
        at io.josemmo.bukkit.plugin.utils.SelectBlockTask$SelectBlockTaskListener.onBlockInteraction(SelectBlockTask.java:135) ~[YamipaPlugin-1.2.10.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:git-PufferfishPlusPurpur-19]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.level.ServerPlayerGameMode.a(ServerPlayerGameMode.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.util.thread.BlockableEventLoop.d(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.d(ReentrantBlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.util.thread.BlockableEventLoop.x(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.util.thread.BlockableEventLoop.c(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast net.minecraft.network.protocol.BundleDelimiterPacket to net.minecraft.network.protocol.BundlePacket
        at java.lang.Class.cast(Class.java:3889) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:41) ~[ProtocolLib #638.jar:?]
        ... 35 more

**Comment by Agaloth** [comment]
This is my protocollib version:

[15:36:22 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-638

**Comment by josemmo** [comment]
Hello @Agaloth,

Upgrading to the [latest ProtocolLib dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) (642 or greater) should fix the problem.

**Comment by josemmo** [comment]
Please provide more details about your server (version, plugins and versions).

**Comment by josemmo** [comment]
UniverseSpigot is not officially supported, for a list of supported platforms see [this link](https://github.com/josemmo/yamipa?tab=readme-ov-file#requirements).
